//
//  KeyCodes.swift
//  ScriptKit
//
//  Created by Silvan Mosberger on 22/07/16.
//  
//

// AFTER THIS LINE GOES AUTOMATICALLY GENERATED CODE, EVERYTHING YOU PUT THERE WILL BE DELETED ON THE NEXT GENERATION
// (This is the generators keyword ->) DOIT

public extension Hotkey {
	/// Virtual keycodes defined in [`Carbon.HIToolbox.Events.h`](/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/Events.h)
	public enum Key : UInt32, CustomStringConvertible, Equatable {
		case ANSI_A = 0x00
		case ANSI_S = 0x01
		case ANSI_D = 0x02
		case ANSI_F = 0x03
		case ANSI_H = 0x04
		case ANSI_G = 0x05
		case ANSI_Z = 0x06
		case ANSI_X = 0x07
		case ANSI_C = 0x08
		case ANSI_V = 0x09
		case ANSI_B = 0x0B
		case ANSI_Q = 0x0C
		case ANSI_W = 0x0D
		case ANSI_E = 0x0E
		case ANSI_R = 0x0F
		case ANSI_Y = 0x10
		case ANSI_T = 0x11
		case ANSI_1 = 0x12
		case ANSI_2 = 0x13
		case ANSI_3 = 0x14
		case ANSI_4 = 0x15
		case ANSI_6 = 0x16
		case ANSI_5 = 0x17
		case ANSI_Equal = 0x18
		case ANSI_9 = 0x19
		case ANSI_7 = 0x1A
		case ANSI_Minus = 0x1B
		case ANSI_8 = 0x1C
		case ANSI_0 = 0x1D
		case ANSI_RightBracket = 0x1E
		case ANSI_O = 0x1F
		case ANSI_U = 0x20
		case ANSI_LeftBracket = 0x21
		case ANSI_I = 0x22
		case ANSI_P = 0x23
		case ANSI_L = 0x25
		case ANSI_J = 0x26
		case ANSI_Quote = 0x27
		case ANSI_K = 0x28
		case ANSI_Semicolon = 0x29
		case ANSI_Backslash = 0x2A
		case ANSI_Comma = 0x2B
		case ANSI_Slash = 0x2C
		case ANSI_N = 0x2D
		case ANSI_M = 0x2E
		case ANSI_Period = 0x2F
		case ANSI_Grave = 0x32
		case ANSI_KeypadDecimal = 0x41
		case ANSI_KeypadMultiply = 0x43
		case ANSI_KeypadPlus = 0x45
		case ANSI_KeypadClear = 0x47
		case ANSI_KeypadDivide = 0x4B
		case ANSI_KeypadEnter = 0x4C
		case ANSI_KeypadMinus = 0x4E
		case ANSI_KeypadEquals = 0x51
		case ANSI_Keypad0 = 0x52
		case ANSI_Keypad1 = 0x53
		case ANSI_Keypad2 = 0x54
		case ANSI_Keypad3 = 0x55
		case ANSI_Keypad4 = 0x56
		case ANSI_Keypad5 = 0x57
		case ANSI_Keypad6 = 0x58
		case ANSI_Keypad7 = 0x59
		case ANSI_Keypad8 = 0x5B
		case ANSI_Keypad9 = 0x5C
		case Return = 0x24
		case Tab = 0x30
		case Space = 0x31
		case Delete = 0x33
		case Escape = 0x35
		case Command = 0x37
		case Shift = 0x38
		case CapsLock = 0x39
		case Option = 0x3A
		case Control = 0x3B
		case RightCommand = 0x36
		case RightShift = 0x3C
		case RightOption = 0x3D
		case RightControl = 0x3E
		case Function = 0x3F
		case F17 = 0x40
		case VolumeUp = 0x48
		case VolumeDown = 0x49
		case Mute = 0x4A
		case F18 = 0x4F
		case F19 = 0x50
		case F20 = 0x5A
		case F5 = 0x60
		case F6 = 0x61
		case F7 = 0x62
		case F3 = 0x63
		case F8 = 0x64
		case F9 = 0x65
		case F11 = 0x67
		case F13 = 0x69
		case F16 = 0x6A
		case F14 = 0x6B
		case F10 = 0x6D
		case F12 = 0x6F
		case F15 = 0x71
		case Help = 0x72
		case Home = 0x73
		case PageUp = 0x74
		case ForwardDelete = 0x75
		case F4 = 0x76
		case End = 0x77
		case F2 = 0x78
		case PageDown = 0x79
		case F1 = 0x7A
		case LeftArrow = 0x7B
		case RightArrow = 0x7C
		case DownArrow = 0x7D
		case UpArrow = 0x7E
		case ISO_Section = 0x0A
		case JIS_Yen = 0x5D
		case JIS_Underscore = 0x5E
		case JIS_KeypadComma = 0x5F
		case JIS_Eisu = 0x66
		case JIS_Kana = 0x68


		public var description : String {
			switch self {
			case .ANSI_A: return "A"
			case .ANSI_S: return "S"
			case .ANSI_D: return "D"
			case .ANSI_F: return "F"
			case .ANSI_H: return "H"
			case .ANSI_G: return "G"
			case .ANSI_Z: return "Z"
			case .ANSI_X: return "X"
			case .ANSI_C: return "C"
			case .ANSI_V: return "V"
			case .ANSI_B: return "B"
			case .ANSI_Q: return "Q"
			case .ANSI_W: return "W"
			case .ANSI_E: return "E"
			case .ANSI_R: return "R"
			case .ANSI_Y: return "Y"
			case .ANSI_T: return "T"
			case .ANSI_1: return "1"
			case .ANSI_2: return "2"
			case .ANSI_3: return "3"
			case .ANSI_4: return "4"
			case .ANSI_6: return "6"
			case .ANSI_5: return "5"
			case .ANSI_Equal: return "Equal"
			case .ANSI_9: return "9"
			case .ANSI_7: return "7"
			case .ANSI_Minus: return "Minus"
			case .ANSI_8: return "8"
			case .ANSI_0: return "0"
			case .ANSI_RightBracket: return "RightBracket"
			case .ANSI_O: return "O"
			case .ANSI_U: return "U"
			case .ANSI_LeftBracket: return "LeftBracket"
			case .ANSI_I: return "I"
			case .ANSI_P: return "P"
			case .ANSI_L: return "L"
			case .ANSI_J: return "J"
			case .ANSI_Quote: return "Quote"
			case .ANSI_K: return "K"
			case .ANSI_Semicolon: return "Semicolon"
			case .ANSI_Backslash: return "Backslash"
			case .ANSI_Comma: return "Comma"
			case .ANSI_Slash: return "Slash"
			case .ANSI_N: return "N"
			case .ANSI_M: return "M"
			case .ANSI_Period: return "Period"
			case .ANSI_Grave: return "Grave"
			case .ANSI_KeypadDecimal: return "KeypadDecimal"
			case .ANSI_KeypadMultiply: return "KeypadMultiply"
			case .ANSI_KeypadPlus: return "KeypadPlus"
			case .ANSI_KeypadClear: return "KeypadClear"
			case .ANSI_KeypadDivide: return "KeypadDivide"
			case .ANSI_KeypadEnter: return "KeypadEnter"
			case .ANSI_KeypadMinus: return "KeypadMinus"
			case .ANSI_KeypadEquals: return "KeypadEquals"
			case .ANSI_Keypad0: return "Keypad0"
			case .ANSI_Keypad1: return "Keypad1"
			case .ANSI_Keypad2: return "Keypad2"
			case .ANSI_Keypad3: return "Keypad3"
			case .ANSI_Keypad4: return "Keypad4"
			case .ANSI_Keypad5: return "Keypad5"
			case .ANSI_Keypad6: return "Keypad6"
			case .ANSI_Keypad7: return "Keypad7"
			case .ANSI_Keypad8: return "Keypad8"
			case .ANSI_Keypad9: return "Keypad9"
			case .Return: return "Return"
			case .Tab: return "Tab"
			case .Space: return "Space"
			case .Delete: return "Delete"
			case .Escape: return "Escape"
			case .Command: return "Command"
			case .Shift: return "Shift"
			case .CapsLock: return "CapsLock"
			case .Option: return "Option"
			case .Control: return "Control"
			case .RightCommand: return "RightCommand"
			case .RightShift: return "RightShift"
			case .RightOption: return "RightOption"
			case .RightControl: return "RightControl"
			case .Function: return "Function"
			case .F17: return "F17"
			case .VolumeUp: return "VolumeUp"
			case .VolumeDown: return "VolumeDown"
			case .Mute: return "Mute"
			case .F18: return "F18"
			case .F19: return "F19"
			case .F20: return "F20"
			case .F5: return "F5"
			case .F6: return "F6"
			case .F7: return "F7"
			case .F3: return "F3"
			case .F8: return "F8"
			case .F9: return "F9"
			case .F11: return "F11"
			case .F13: return "F13"
			case .F16: return "F16"
			case .F14: return "F14"
			case .F10: return "F10"
			case .F12: return "F12"
			case .F15: return "F15"
			case .Help: return "Help"
			case .Home: return "Home"
			case .PageUp: return "PageUp"
			case .ForwardDelete: return "ForwardDelete"
			case .F4: return "F4"
			case .End: return "End"
			case .F2: return "F2"
			case .PageDown: return "PageDown"
			case .F1: return "F1"
			case .LeftArrow: return "LeftArrow"
			case .RightArrow: return "RightArrow"
			case .DownArrow: return "DownArrow"
			case .UpArrow: return "UpArrow"
			case .ISO_Section: return "Section"
			case .JIS_Yen: return "Yen"
			case .JIS_Underscore: return "Underscore"
			case .JIS_KeypadComma: return "KeypadComma"
			case .JIS_Eisu: return "Eisu"
			case .JIS_Kana: return "Kana"
			}
		}

	}
}
